sales_order/urls.py
# -*- encoding: utf-8 -*-
from django.urls import re_path

from .views import (
    SalesOrderContactListView,
    SalesOrderCreateView,
    SalesOrderListView,
    SalesOrderUpdateView,
)


urlpatterns = [
    re_path(r"^$", view=SalesOrderListView.as_view(), name="sales.order.list"),
    re_path(
        r"^(?P<pk>\d+)/update/$",
        view=SalesOrderUpdateView.as_view(),
        name="sales.order.update",
    ),
    re_path(
        r"^contact/(?P<contact_pk>\d+)/$",
        view=SalesOrderContactListView.as_view(),
        name="sales.order.contact.list",
    ),
    re_path(
        r"^contact/(?P<contact_pk>\d+)/create/$",
        view=SalesOrderCreateView.as_view(),
        name="sales.order.create",
    ),
]

sales_order/models.py
# -*- encoding: utf-8 -*-
import logging

from decimal import Decimal

from django.apps import apps
from django.conf import settings
from django.core.exceptions import ObjectDoesNotExist
from django.db import models
from reversion import revisions as reversion

from base.model_utils import (
    TimedCreateModifyDeleteVersionModel,
    TimedCreateModifyDeleteVersionModelManager,
    TimeStampedModel,
)


logger = logging.getLogger(__name__)


def get_contact_model():
    return apps.get_model(settings.CONTACT_MODEL)


class SalesOrderError(Exception):
    def __init__(self, value):
        Exception.__init__(self)
        self.value = value

    def __str__(self):
        return repr("%s, %s" % (self.__class__.__name__, self.value))


class SalesOrderTypeManager(models.Manager):
    def _create_sales_order_type(self, title, is_estimated):
        x = self.model(title=title, is_estimated=is_estimated)
        x.save()
        return x

    def init_sales_order_type(self, title, is_estimated):
        try:
            x = self.get(title=title)
            x.is_estimated = is_estimated
            x.save()
        except self.model.DoesNotExist:
            x = self._create_sales_order_type(title, is_estimated)
        return x


@reversion.register()
class SalesOrderType(TimeStampedModel):
    """Type of sales order.

    1. Do we even need a type?
    2. I think ``is_estimated`` is probably the wrong field name.
       The type of a sales order could be:

       - Agreed by email
       - Agreed by prior arrangement
       - Fixed Price
       - Support Contract

       So do we need ``is_estimated`` at all?

    """

    title = models.CharField(max_length=100)
    is_estimated = models.BooleanField(default=False)
    objects = SalesOrderTypeManager()

    class Meta:
        ordering = ("title",)
        verbose_name = "Sales Order Type"

    def __str__(self):
        return "{}".format(self.title)


class SalesOrderManager(TimedCreateModifyDeleteVersionModelManager):
    """Sales order model manager.

    You can find an ``_init_sales_order`` method in::

      kbsoftware_couk/project/management/commands/4473-create-sales-order.py

    """

    def current(self, contact=None):
        qs = self.model.objects.exclude(deleted=True)
        if contact is None:
            pass
        else:
            qs = qs.filter(contact=contact)
        return qs


@reversion.register()
class SalesOrder(TimedCreateModifyDeleteVersionModel):
    """Sales order.

    A sales order is created for a ``Contact`` (not for a ticket).

    ``sales_order_type``
      I am not sure what this is used for... Could be an estimate?
    ``hours``
      Number of hours agreed with the customer.
    ``hours_type``
      Determines if the ticket is fixed price (``FIXED_PRICE``) or not.
    ``value``
      Value of the work agreed with the customer.
    ``start_date`` and ``end_date``
      Period of time when this sales order is valid e.g. for yearly contracts.
    ``maximum_hours_per_ticket``
      Several of our customers let us do ``x`` hours of work on a ticket without
      checking first.  Work exceeding ``maximum_hours_per_ticket`` will need a
      separate sales order.
    ``completed``
      Has this sales order been completed?

    """

    UNIQUE_FIELD_NAME = "number"
    UNIQUE_FIELD_NAME_CATEGORY = None

    # HOURS_PER_MONTH = "hours-per-month"
    FIXED_PRICE = "fixed-price"
    HOURS_PER_MONTH = "hours-per-month"
    HOURS_PER_TICKET = "hours-per-ticket"
    HOURS_TOTAL = "hours-total"
    NO_LIMIT = "no-limit"
    SUPPORT_ANNUAL = "support-annual"
    SUPPORT_MONTHLY = "support-monthly"

    HOURS_TYPE = (
        (HOURS_TOTAL, "Total Hours"),
        (HOURS_PER_MONTH, "Hours per Month"),
        (HOURS_PER_TICKET, "Hours per Ticket"),
        (FIXED_PRICE, "Fixed Price (Value of Sales Order)"),
        (NO_LIMIT, "No Limit"),
        (SUPPORT_ANNUAL, "Annual Support / Maintenance"),
        (SUPPORT_MONTHLY, "Monthly Support / Maintenance"),
    )

    number = models.IntegerField(default=0)
    contact = models.ForeignKey(
        settings.CONTACT_MODEL, on_delete=models.CASCADE
    )
    title = models.CharField(max_length=100)
    sales_order_type = models.ForeignKey(
        SalesOrderType, on_delete=models.CASCADE
    )
    description = models.TextField(blank=True, null=True)
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, related_name="+", on_delete=models.CASCADE
    )
    # estimated = models.BooleanField()
    hours = models.IntegerField(
        blank=True, null=True, help_text="Hours agreed with client"
    )
    hours_type = models.SlugField(
        max_length=20,
        choices=HOURS_TYPE,
        default=HOURS_TOTAL,
        help_text="Hours limited by",
    )
    value = models.DecimalField(
        blank=True,
        null=True,
        max_digits=8,
        decimal_places=2,
        help_text="Value of sales order",
    )
    start_date = models.DateField(
        blank=True, null=True, help_text="Start date of support contract"
    )
    end_date = models.DateField(
        blank=True, null=True, help_text="End date of support contract"
    )
    # 29/12/2023, This field is also used for 'maximum_hours_per_month'
    maximum_hours_per_ticket = models.IntegerField(
        blank=True,
        null=True,
        help_text="No charge for work taking longer (per month / per ticket)",
    )
    completed = models.BooleanField(
        default=False, help_text="Complete date (if not a support contract)"
    )
    completed_date = models.DateTimeField(blank=True, null=True)
    completed_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        blank=True,
        null=True,
        related_name="+",
        on_delete=models.CASCADE,
    )
    objects = SalesOrderManager()

    class Meta:
        ordering = ("-number",)
        unique_together = ("number", "deleted_version")
        verbose_name = "Sales Order"
        verbose_name_plural = "Sales Orders"

    def __str__(self):
        return "{}: {} for {}".format(
            self.number, self.title, self.contact.full_name
        )

    def hourly_rate_for_contact(self):
        result = None
        try:
            invoice_contact = self.contact.invoicecontact
        except ObjectDoesNotExist:
            raise SalesOrderError(
                f"Contact ('{self.contact.user.username}') "
                "has no 'InvoiceContact' (for the 'hourly_rate') "
                f"(for sales order {self.number})"
            )
        if invoice_contact.hourly_rate:
            result = invoice_contact.hourly_rate
        else:
            raise SalesOrderError(
                f"Contact ('{self.contact.user.username}') has "
                f"no 'hourly_rate' (for sales order {self.number})"
            )
        return result

    def maximum_value(self):
        result = None
        if self.hours_type == self.HOURS_TOTAL:
            if self.hours and self.hours > Decimal():
                result = Decimal(self.hours) * self.hourly_rate_for_contact()
            else:
                raise SalesOrderError(
                    f"Sales order is '{self.hours_type}', but "
                    "'hours' has not been set"
                )
        return result

    def maximum_value_per_ticket(self):
        result = None
        if self.hours_type == self.HOURS_PER_TICKET:
            if (
                self.maximum_hours_per_ticket
                and self.maximum_hours_per_ticket > Decimal()
            ):
                result = (
                    Decimal(self.maximum_hours_per_ticket)
                    * self.hourly_rate_for_contact()
                )
            else:
                raise SalesOrderError(
                    f"Sales order is '{self.hours_type}', but the "
                    "'maximum_hours_per_ticket' has not been set"
                )
        return result

    @property
    def sales_order_number(self):
        return "{:06d}".format(self.number)

    def summary(self):
        """Summary of the sales order for 'time-record-pandas'.

        ::

          invoice/management/commands/time-record-pandas.py

        """
        result = {
            "contact": self.contact.user.username,
            "sales-order-number": self.sales_order_number,
            "title": self.title,
        }
        try:
            result.update({"hourly-rate": self.hourly_rate_for_contact()})
        except SalesOrderError:
            pass
        if self.hours_type:
            result.update({"hours-type": self.get_hours_type_display()})
        if self.value:
            result.update({"value": self.value})
        return result

sales_order/forms.py
# -*- encoding: utf-8 -*-
from django import forms

from base.form_utils import RequiredFieldForm
from .models import SalesOrder


class SalesOrderEmptyForm(forms.ModelForm):
    class Meta:
        model = SalesOrder
        fields = ()


class SalesOrderForm(RequiredFieldForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["title"].widget.attrs.update({"class": "pure-input-1"})
        self.fields["description"].widget.attrs.update(
            {"class": "pure-input-1", "rows": 5}
        )
        for name in ("hours_type", "sales_order_type"):
            self.fields[name].widget.attrs.update({"class": "chosen-select"})
        self.fields["maximum_hours_per_ticket"].label = (
            "Maximum hours per month / per ticket"
        )

    class Meta:
        model = SalesOrder
        fields = [
            "title",
            "sales_order_type",
            "description",
            # "estimated",
            "hours",
            "hours_type",
            "value",
            "start_date",
            "end_date",
            "maximum_hours_per_ticket",
        ]

    def clean(self):
        cleaned_data = super().clean()
        hours = cleaned_data.get("hours")
        maximum_hours = cleaned_data.get("maximum_hours_per_ticket")
        value = cleaned_data.get("value")
        start_date = cleaned_data.get("start_date")
        end_date = cleaned_data.get("end_date")
        if (
            (hours and maximum_hours)
            or (maximum_hours and value)
            or (hours and value)
        ):
            raise forms.ValidationError(
                "A sales order can be for hours, a value or maximum hours",
                code="sales_order__hours_or_value_or_maximum",
            )
        if start_date or end_date:
            if start_date and end_date:
                if start_date > end_date:
                    raise forms.ValidationError(
                        "The start date must be before the end date",
                        code="sales_order__start_before_end",
                    )
            else:
                raise forms.ValidationError(
                    "If a sales order has a start date or "
                    "end date, it must have both",
                    code="sales_order__start_and_end_date",
                )
        return cleaned_data

sales_order/views.py
# -*- encoding: utf-8 -*-
from braces.views import LoginRequiredMixin, StaffuserRequiredMixin
from django.urls import reverse
from django.views.generic import CreateView, DetailView, ListView, UpdateView

from base.view_utils import BaseMixin
from .forms import SalesOrderForm
from .models import get_contact_model, SalesOrder


class SalesOrderContactListView(
    LoginRequiredMixin, StaffuserRequiredMixin, BaseMixin, ListView
):
    paginate_by = 20

    def _contact(self):
        pk = self.kwargs["contact_pk"]
        return get_contact_model().objects.get(pk=pk)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(dict(contact=self._contact()))
        return context

    def get_queryset(self):
        contact = self._contact()
        return SalesOrder.objects.current(contact)


class SalesOrderCreateView(
    LoginRequiredMixin, StaffuserRequiredMixin, BaseMixin, CreateView
):
    form_class = SalesOrderForm
    model = SalesOrder

    def _contact(self):
        pk = self.kwargs["contact_pk"]
        return get_contact_model().objects.get(pk=pk)

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.number = self.model.objects.next_number()
        self.object.completed = False
        self.object.contact = self._contact()
        self.object.user = self.request.user
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(dict(contact=self._contact()))
        return context

    def get_success_url(self):
        return reverse(
            "sales.order.contact.list", args=[self.object.contact.pk]
        )


class SalesOrderListView(
    LoginRequiredMixin, StaffuserRequiredMixin, BaseMixin, ListView
):
    paginate_by = 20

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(dict(contact=None))
        return context

    def get_queryset(self):
        return SalesOrder.objects.current()


class SalesOrderUpdateView(
    LoginRequiredMixin, StaffuserRequiredMixin, BaseMixin, UpdateView
):
    form_class = SalesOrderForm
    model = SalesOrder

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(dict(contact=self.object.contact))
        return context

    def get_success_url(self):
        return reverse("sales.order.detail", args=[self.object.pk])

sales_order/templates/sales_order/_sales_order_detail_header.html
<tr valign="top">
  <td>
    <strong>
      Contact
    </strong>
  </td>
  <td>
    <a href="{% url 'contact.detail' sales_order.contact.pk %}">
      <strong>{{ sales_order.contact.full_name }}</strong>
    </a>
    <br>
    {{ sales_order.contact.address|linebreaksbr }}
  </td>
</tr>
<tr valign="top">
  <td>
    <strong>
      Type
    </strong>
  </td>
  <td>
    {{ sales_order.get_hours_type_display }}
    <small>
      ({{ sales_order.sales_order_type.title }})
    </small>
  </td>
</tr>
<tr valign="top">
  <td>
    <strong>
      Title
    </strong>
  </td>
  <td>
    {{ sales_order.title }}
  </td>
</tr>
{% if sales_order.description %}
  <tr valign="top">
    <td>Description</td>
    <td>
      {{ sales_order.description|linebreaksbr }}
    </td>
  </tr>
{% endif %}

sales_order/templates/sales_order/_sales_order_detail_left.html
<tr>
  <td>
    <strong>
      Created
    </strong>
  </td>
  <td>
    {{ sales_order.created|date:'d/m/Y' }}
  </td>
</tr>
<tr>
  <td>
    <strong>
      Created By
    </strong>
  </td>
  <td>
    {{ sales_order.user.get_full_name }}
  </td>
</tr>

sales_order/templates/sales_order/_sales_order_detail_right.html
{% if sales_order.hours %}
  <tr>
    <td>
      <strong>
        Hours
      </strong>
    </td>
    <td>
      {{ sales_order.hours }}
      {{ sales_order.get_hours_type_display }}
    </td>
  </tr>
{% endif %}
{% if sales_order.value %}
  <tr>
    <td>
      <strong>
        Value
      </strong>
    </td>
    <td>
      &pound;{{ sales_order.value }}
    </td>
  </tr>
{% endif %}
{% if sales_order.start_date %}
  <tr>
    <td>
      <strong>
        Contracted
      </strong>
    </td>
    <td>
      From
      {{ sales_order.start_date|date:'d/m/Y' }}
      to
      {{ sales_order.end_date|date:'d/m/Y' }}
    </td>
  </tr>
{% endif %}
{% if sales_order.maximum_hours_per_ticket %}
  <tr>
    <td>
      <strong>
        Maximum {{ sales_order.get_hours_type_display }}
      </strong>
    </td>
    <td>
      {{ sales_order.maximum_hours_per_ticket }}
    </td>
  </tr>
{% endif %}

sales_order/templates/sales_order/_sales_order_list.html
<table class="pure-table pure-table-bordered" width="100%">
  <thead>
    <tr valign="top">
      <th>Number</th>
      {% if not contact %}
        <th>Contact</th>
      {% endif %}
      <th>Title</th>
      <th>Value</th>
      <th>Maximum hours per ticket</th>
      <th>Created</th>
    </tr>
  </thead>
  <tbody>
    {% for x in salesorder_list %}
      <tr valign="top">
        <td>
          <a href="{% url 'sales.order.detail' x.pk %}">
            {{ x.sales_order_number }}
          </a>
        </td>
        {% if not contact %}
          <td>
            <a href="{% url 'contact.detail' x.contact.pk %}">
              {{ x.contact.full_name }}
            </a>
          </td>
        {% endif %}
        <td>
          {{ x.title }}
          {% if x.start_date %}
            <small>
              (from
              {{ x.start_date|date:'d/m/Y' }}
              to
              {{ x.end_date|date:'d/m/Y' }})
            </small>
          {% endif %}
        </td>
        <td>
          {% if x.value %}
            &pound;{{ x.value }}
          {% endif %}
          {% if x.hours %}
            {{ x.hours }} hours
          {% endif %}
        </td>
        <td>
          {% if x.maximum_hours_per_ticket %}
            {{ x.maximum_hours_per_ticket }} hours
          {% endif %}
        </td>
        <td>
          {{ x.created|date:'d/m/Y H:i' }}
        </td>
      </tr>
    {% endfor %}
  </tbody>
</table>

sales_order/templates/sales_order/_settings.html
<div class="pure-u-1 pure-u-md-1-4">
  <div class="pure-g">
    <div class="pure-u-1">
      <h4>Sales Order</h4>
    </div>
  </div>
  <div class="r-box">
    <a href="." class="pure-menu-link">
      <i class="fa fa-heartbeat"></i>
      Example
    </a>
  </div>
</div>

sales_order/templates/sales_order/sales_order_report_form.html
{% extends 'dash/base.html' %}

{% block sub_title %}
  Report for Sales Order {{ object.pk }} {{ object.ticket.contact }}
{% endblock sub_title %}

{% block sub_heading %}
  Report for Sales Order {{ object.pk }} {{ object.ticket.contact }}
{% endblock sub_heading %}

{% block content %}
  <div class="pure-g">
    <div class="pure-u-1">
      <div class="pure-menu pure-menu-horizontal">
        <ul class="pure-menu-list">
          <li class="pure-menu-item">
            {% if next %}
              <a href="{{ next }}" class="pure-menu-link">
            {% elif object %}
              <a href="{% url 'sales.order.detail' object.pk %}" class="pure-menu-link">
            {% else %}
              <a href="{% url 'sales.order.list' %}" class="pure-menu-link">
            {% endif %}
            <i class="fa fa-reply"></i>
            {% if object %}
              Sales Order {{ object.pk }}
            {% endif %}
          </a>
        </li>
      </ul>
    </div>
  </div>
  </div>
  <div class="pure-g">
    <div class="pure-u-1">
      {% if object %}
        <strong>
          Sales Order
        </strong>
        {{ object.pk }},
        <strong>
          {{ object.title }}
        </strong>
        for {{ object.contact.get_full_name }}
      {% endif %}
      {% include '_form.html' with submit='Run report...' %}
    </div>
  </div>
{% endblock %}

{% block script_extra %}
  {{ block.super }}
  {% include 'base/_chosen.html' %}
{% endblock script_extra %}

sales_order/templates/sales_order/salesorder_form.html
{% extends 'dash/base.html' %}

{% block sub_title %}
  {% if object %}
    Sales Order {{ object.pk }} for {{ contact }}
  {% else %}
    Create Sales Order
  {% endif %}
{% endblock sub_title %}

{% block sub_heading %}
  {% if object %}
    Sales Order {{ object.pk }} for {{ contact }}
  {% else %}
    Create Sales Order
  {% endif %}
{% endblock sub_heading %}

{% block content %}
  <div class="pure-g">
    <div class="pure-u-1">
      <div class="pure-menu pure-menu-horizontal">
        <ul class="pure-menu-list">
          <li class="pure-menu-item">
            {% if next %}
              <a href="{{ next }}" class="pure-menu-link">
            {% elif object %}
              <a href="{% url 'sales.order.detail' object.pk %}" class="pure-menu-link">
            {% else %}
              <a href="{% url 'sales.order.list' %}" class="pure-menu-link">
            {% endif %}
            <i class="fa fa-reply"></i>
          </a>
        </li>
      </ul>
    </div>
  </div>
  </div>
  <div class="pure-g">
    <div class="pure-u-1">
      {% include '_form.html' with inline_checkbox=True aligned=True %}
    </div>
  </div>
{% endblock %}

{% block script_extra %}
  {{ block.super }}
  {% include 'base/_chosen.html' %}
{% endblock script_extra %}

sales_order/templates/sales_order/salesorder_list.html
{% extends 'dash/base.html' %}
{% load static %}

{% block title %}
  {% if contact %}
    Sales Orders for {{ contact }}
  {% else %}
    All Sales Orders
  {% endif %}
{% endblock title %}

{% block sub_heading %}
  {% if contact %}
    Sales Orders for {{ contact }}
  {% else %}
    All Sales Orders
  {% endif %}
{% endblock sub_heading %}

{% block content %}
  <div class="pure-g">
    <div class="pure-u-1">
      <div class="pure-menu pure-menu-horizontal">
        <ul class="pure-menu-list">
          <li class="pure-menu-item">
            {% if contact %}
              <a href="{% url 'contact.detail' contact.pk %}" class="pure-menu-link">
            {% else %}
              <a href="{% url 'project.dash' %}" class="pure-menu-link">
            {% endif %}
            <i class="fa fa-reply"></i>
          </a>
        </li>
        {% if contact %}
          <li class="pure-menu-item">
            <a href="{% url 'sales.order.create' contact.pk %}" class="pure-menu-link">
              <i class="fa fa-plus"></i>
              Sales Order
            </a>
          </li>
        {% endif %}
        {% include 'base/_paginate.html' %}
      </ul>
    </div>
  </div>
  </div>
  <div class="pure-g">
    <div class="pure-u-1">
      {% include 'sales_order/_sales_order_list.html' %}
    </div>
  </div>
  <div class="pure-g">
    <div class="pure-u-1">
      <div class="pure-menu pure-menu-horizontal">
        <ul class="pure-menu-list">
          {% include 'base/_paginate.html' %}
        </ul>
      </div>
    </div>
  </div>
{% endblock content %}